language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
install: "pip install hypothesis mock"
script: "python -m unittest -v tests.test_connection tests.test_core tests.test_output tests.test_post tests.test_validate tests.test_write"
