language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
install: "pip install hypothesis mock"
script: "python -m unittest -v tests.test_core tests.test_connection tests.test_handle_targets tests.test_output tests.test_validate_input"
